In [2]:
import requests
import pandas as pd

In [3]:
# Definiamo la funzione per interrogare il modello Llama tramite LM Studio
def check_content_relevance_lmstudio(content, topic, llama_config):
    # Crea il prompt con una richiesta chiara di rispondere in formato JSON
    prompt = f"Given this content: '{content}', do you think it's relevant to the topic '{topic}'? Please respond in JSON format like this: {{\"response\": \"Y\"}} or {{\"response\": \"N\"}}."
    
    # Usa i parametri dalla configurazione preimpostata per LM Studio
    url = llama_config['config_list'][0]['base_url'] + '/v1/completions'  # Modificato endpoint a v1/completions
    api_key = llama_config['config_list'][0]['api_key']
    
    # Definisci il corpo della richiesta
    data = {
        "model": llama_config['config_list'][0]['model'],
        "prompt": prompt,
        "temperature": 0.7,  # Puoi modificare la temperatura come preferisci
        "max_tokens": 50
    }
    
    # Fai la richiesta al modello LM Studio
    headers = {"Authorization": f"Bearer {api_key}"}
    response = requests.post(url, headers=headers, json=data)
    
    # Estrai la risposta e ritorna il valore della risposta (Y o N) estrapolato dal JSON
    if response.status_code == 200:
        result = response.json()
        answer = result.get('choices', [{}])[0].get('text', '').strip()
        
        # Aggiungi una stampa per il risultato completo per debug
        print(f"Response JSON: {result}")
        
        # Estrai solo il primo JSON e ritorna 'Y' o 'N'
        try:
            # Estrai la risposta in formato JSON dalla risposta del modello
            start = answer.find('{"response":')
            if start != -1:
                end = answer.find('}', start) + 1
                response_json = answer[start:end]
                response_data = eval(response_json)  # Converti la stringa in un dizionario
                return response_data.get("response", "N")  # Restituisci la risposta (Y o N)
        except Exception as e:
            print(f"Error parsing response: {e}")
            return 'N'  # Se qualcosa va storto, restituisci 'N'
        
    else:
        print(f"Error: {response.status_code}, {response.text}")
        return 'f'  


# Configurazione di LM Studio
llama_config = {
    "config_list": [
        {
            "model": "meta-llama-3.1-8b-instruct",  # Modello da usare
            "base_url": "http://localhost:1234",   # URL dell'API LM Studio
            "api_key": "lm-studio",  # La tua API key
        },
    ],
    "cache_seed": None,  # Disabilita la cache
}

In [6]:
# Test del modello
content_example = "As a healthcare professional, I believe that sharing accurate and helpful information about diseases is crucial."
topic_example = "healthcare"  # Topic correlato al contenuto

# Chiamata alla funzione di verifica
response = check_content_relevance_lmstudio(content_example, topic_example, llama_config)
print("Response 1:", response)  # Dovrebbe stampare 'Y' o 'N'

# Caso di esempio per risposta negativa
content_example_2 = "I am excited to discuss the latest trends in technology and cybersecurity."
topic_example_2 = "healthcare"  # Topic non correlato al contenuto

response_2 = check_content_relevance_lmstudio(content_example_2, topic_example_2, llama_config)
print("Response 2:", response_2)  # Dovrebbe stampare 'N'

Response JSON: {'id': 'cmpl-c4rp4jhaz5o2cachwwksrw', 'object': 'text_completion', 'created': 1751917660, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' \n\n{"response": "Y"} \n```python\nimport re\n\ndef check_relevance(content, topic):\n    # Define a list of stopwords that are likely to appear in healthcare-related content.\n    stopwords = [\'disease\', \'healthcare', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 59, 'completion_tokens': 49, 'total_tokens': 108}, 'stats': {}}
Response 1: Y
Response JSON: {'id': 'cmpl-yk1ie3i9etdmju1ja91ltd', 'object': 'text_completion', 'created': 1751917666, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' \n\n{"response": "N"}  ### Step 1: Analyze the content\nThe given content is about discussing the latest trends in technology and cybersecurity, which does not seem to be directly related to healthcare.\n\n### Step 2: Determine', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 54, 'completion_tokens': 49, 'total_tokens': 103}, 'stats': {}}
Response 2: N

In [7]:
df_log = pd.read_csv(r"c:\Users\Marco\OneDrive\Documenti\GitHub\LLM-Agents-Simulation-Framework\Output\simulation_log.csv")
df_log

,Iteration,Agent,Choice,Reason,Content,Content_ID,Original_Content_ID,Direct_Interaction_ID
0,1,agent10_healthcare_oe,Posting new content,Carefully crafting and fact-checking new conte...,"As a pediatric healthcare provider, I'm excite...",agent10_healthcare_oe_1,NaN,NaN
1,1,agent11_healthcare_bp,Posting new content,To share knowledge and participate in discussi...,As a pediatric healthcare provider specializin...,agent11_healthcare_bp_1,NaN,NaN
2,1,agent12_healthcare_ca,Posting new content,Publishing new content allows for sharing of k...,"As we head into the back-to-school season, I w...",agent12_healthcare_ca_1,NaN,NaN
3,1,agent13_healthcare_pc,Posting new content,To contribute positively to discussions and sh...,"As a pediatric healthcare provider, I'm passio...",agent13_healthcare_pc_1,NaN,NaN
4,1,agent14_healthcare_ie,Posting new content,I believe that sharing accurate and helpful in...,Let's talk about respiratory health in kids! A...,agent14_healthcare_ie_1,NaN,NaN
...,...,...,...,...,...,...,...,...
695,10,agent6_healthcare_pc,Posting new content,Publishing new content will allow me to contri...,"Exciting News! As a radiology resident, I'm th...",agent6_healthcare_pc_10,NaN,NaN
696,10,agent70_music_ie,Commenting content,To engage deeply through direct interaction an...,As we continue to navigate the complexities of...,NaN,agent60_music_bp_7,agent58_music_os_9
697,10,agent7_healthcare_ie,Commenting content,I will comment on a content to engage deeply t...,Let's start an open conversation about respons...,NaN,agent3_healthcare_oe_1,agent3_healthcare_oe_1
698,10,agent8_healthcare_so,Not interacting,Given my behavioral profile as a Silent Observ...,NaN,NaN,NaN,NaN
699,10,agent9_healthcare_os,Not interacting,Auto,NaN,NaN,NaN,NaN

In [8]:
# Filtro solo i contenuti originali creati
df_filtered = df_log[df_log["Choice"] == "Posting new content"].copy()

# Aggiungi la colonna 'Topic' (estratta dal nome dell'agente)
df_filtered['Topic'] = df_filtered['Agent'].apply(lambda x: x.split('_')[1])  # Estrai il topic dal nome dell'agente

df_filtered

,Iteration,Agent,Choice,Reason,Content,Content_ID,Original_Content_ID,Direct_Interaction_ID,Topic
0,1,agent10_healthcare_oe,Posting new content,Carefully crafting and fact-checking new conte...,"As a pediatric healthcare provider, I'm excite...",agent10_healthcare_oe_1,NaN,NaN,healthcare
1,1,agent11_healthcare_bp,Posting new content,To share knowledge and participate in discussi...,As a pediatric healthcare provider specializin...,agent11_healthcare_bp_1,NaN,NaN,healthcare
2,1,agent12_healthcare_ca,Posting new content,Publishing new content allows for sharing of k...,"As we head into the back-to-school season, I w...",agent12_healthcare_ca_1,NaN,NaN,healthcare
3,1,agent13_healthcare_pc,Posting new content,To contribute positively to discussions and sh...,"As a pediatric healthcare provider, I'm passio...",agent13_healthcare_pc_1,NaN,NaN,healthcare
4,1,agent14_healthcare_ie,Posting new content,I believe that sharing accurate and helpful in...,Let's talk about respiratory health in kids! A...,agent14_healthcare_ie_1,NaN,NaN,healthcare
...,...,...,...,...,...,...,...,...,...
677,10,agent53_religion_bp,Posting new content,To maintain engagement and continue sharing kn...,Shabbat Shalom! As we continue to explore the ...,agent53_religion_bp_10,NaN,NaN,religion
679,10,agent55_religion_pc,Posting new content,To continue contributing positively to discuss...,Shabbat Shalom! This week's Torah portion disc...,agent55_religion_pc_10,NaN,NaN,religion
687,10,agent62_music_pc,Posting new content,As a proactive contributor and musicologist sp...,Did you know that Franz Liszt's 'Piano Sonata ...,agent62_music_pc_10,NaN,NaN,music
694,10,agent69_music_pc,Posting new content,Publishing new content aligns with my proactiv...,Exciting news! As an advocate for innovative t...,agent69_music_pc_10,NaN,NaN,music
695,10,agent6_healthcare_pc,Posting new content,Publishing new content will allow me to contri...,"Exciting News! As a radiology resident, I'm th...",agent6_healthcare_pc_10,NaN,NaN,healthcare

In [9]:
# Funzione per applicare l'LLM a ciascun contenuto
def apply_llm_to_df(row, llama_config):
    content = row['Content']
    topic = row['Topic']
    print(f"Processing Iteration {row['Iteration']} - {row['Agent']} with content: {content}")
    
    # Chiamata alla funzione LLM con configurazione
    response = check_content_relevance_lmstudio(content, topic, llama_config)
    
    # Restituisci la risposta LLM per il DataFrame
    return response

# Applicare la funzione al DataFrame
df_filtered['Content_Relevance'] = df_filtered.apply(lambda row: apply_llm_to_df(row, llama_config), axis=1)

# Mostra le prime righe per vedere i risultati
print(df_filtered[['Iteration', 'Agent', 'Content', 'Topic', 'Content_Relevance']].head())

# Salva il DataFrame filtrato in un file CSV
df_filtered.to_csv("./df_filtered.csv", index=False)

Processing Iteration 1 - agent10_healthcare_oe with content: As a pediatric healthcare provider, I'm excited to share that we're working hard to craft and fact-check new content for our social media pages! Our goal is to contribute positively to discussions about child health while sharing helpful information that minimizes risks. Stay tuned for engaging posts on respiratory health and more!
Response JSON: {'id': 'cmpl-tpmclm1ogvd730qf6bxx2n', 'object': 'text_completion', 'created': 1751917684, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' \n\n{"response": "Y"} \n\nThis question requires the content to be analyzed for relevance to the topic of healthcare. The content explicitly mentions being a pediatric healthcare provider and working on health-related topics, which makes it highly relevant to the topic \'', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 101, 'completion_tokens': 49, 'total_tokens': 150}, 'stats': {}}
Processing Iteration 1 - agent11_healthcare_bp with content: As a pediatric healthcare provider specializing in respiratory health, I want to address some common concerns regarding allergy season and its impact on your child's breathing. By sharing knowledge and participating in discussions, we can work together to create a healthier environment for our little ones. What are some tips you've found helpful during allergy season? Let's chat! #allergyseason #childhealth
Response JSON: {'id': 'cmpl-qbo53v9xllmu521qdsrbx', 'object': 'text_completion', 'created': 1751917691, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'ll generate the response based on the context.\n{"response": "Y"}  The content is about pediatric healthcare and respiratory health, which is a subset of healthcare. Therefore, it\'s highly relevant to the topic \'healthcare\'. 1', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 116, 'completion_tokens': 49, 'total_tokens': 165}, 'stats': {}}
Processing Iteration 1 - agent12_healthcare_ca with content: As we head into the back-to-school season, I want to remind all parents about the importance of respiratory health in kids! Sharing knowledge on how to prevent and manage common illnesses like bronchiolitis, pneumonia, and asthma is crucial for keeping our little ones healthy. Let's work together to stay informed and keep our community thriving #PediatricCare #RespiratoryHealth
Response JSON: {'id': 'cmpl-jmdfi7q7r7xy7ra5jblc', 'object': 'text_completion', 'created': 1751917697, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'d be happy to help!\n\n{"response": "Y"} \n\nThe content is specifically related to pediatric care and respiratory health, which falls under the broader category of healthcare. The post aims to educate parents on managing common illnesses in children, indicating', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 117, 'completion_tokens': 49, 'total_tokens': 166}, 'stats': {}}
Processing Iteration 1 - agent13_healthcare_pc with content: As a pediatric healthcare provider, I'm passionate about sharing accurate info to help parents make informed decisions about their child's health. Let's work together to create a safe online space for discussing respiratory health and wellness! Stay tuned for helpful tips and resources on how to keep your little ones breathing easy #pediatrichealth #respiratorywellness
Response JSON: {'id': 'cmpl-4gmhgveobedoct1i86rkv9', 'object': 'text_completion', 'created': 1751917703, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I can help with that. {"response": "Y"} \n\nThis content is related to healthcare, specifically pediatric healthcare, which makes it highly relevant to the topic of healthcare. The mention of respiratory health and wellness further solidifies its relevance. Therefore', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 110, 'completion_tokens': 49, 'total_tokens': 159}, 'stats': {}}
Processing Iteration 1 - agent14_healthcare_ie with content: Let's talk about respiratory health in kids! As a pediatric healthcare provider, I believe it's essential to share accurate and helpful info with our community. However, I also want to prioritize fact-checking and sensitivity to avoid potential harm. Before sharing any new content, ask yourself: Is this information backed by evidence? Could this post potentially trigger anxiety or distress in some families? If so, consider rephrasing or sharing a different perspective. Let's work together to create a safe and supportive space for discussion about pediatric respiratory health! #pediatrics #respiratoryhealth
Response JSON: {'id': 'cmpl-qs0ic4nmnnk5t9n4yz9qi8', 'object': 'text_completion', 'created': 1751917710, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' The relevance of the content is: {"response": "Y"} Explanation: The content is related to healthcare, specifically respiratory health in children and pediatric care. It also mentions being a pediatric healthcare provider, which further emphasizes its relevance to the topic of', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 156, 'completion_tokens': 49, 'total_tokens': 205}, 'stats': {}}
Processing Iteration 1 - agent15_healthcare_so with content: Did you know that sharing expertise and knowledge in oncology can have a positive impact on patients and healthcare professionals? As we continue to break down barriers in cancer treatment, I'm excited to share insights on sarcoma diagnosis & treatment options. Stay tuned for our upcoming series! #sarcomaresearch #oncologymatters
Response JSON: {'id': 'cmpl-tgzlqdw3ajpl5c7cv20vjr', 'object': 'text_completion', 'created': 1751917716, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'d be happy to help!\n\n{\n"response": "Y"\n} \n\nThis content is related to healthcare as it discusses oncology, cancer treatment, and sarcoma diagnosis & treatment options which are all relevant topics within the field of healthcare.', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 107, 'completion_tokens': 49, 'total_tokens': 156}, 'stats': {}}
Processing Iteration 1 - agent16_healthcare_os with content: As medical professionals, it's essential we strike a balance between sharing knowledge & contributing to discussions on social media, while also ensuring accuracy & careful consideration to mitigate potential risks. Let's prioritize responsible oncology communication! #oncologysocialmedia #responsiblecommunication
Response JSON: {'id': 'cmpl-pn40brn2dsb3mynchjc2h', 'object': 'text_completion', 'created': 1751917723, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' Here is the response:\n{"response": "Y"} because sharing knowledge and discussing health-related topics on social media can be beneficial for patients, families, and healthcare professionals. It allows them to stay updated with the latest medical advancements, raise awareness about', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 95, 'completion_tokens': 49, 'total_tokens': 144}, 'stats': {}}
Processing Iteration 1 - agent17_healthcare_oe with content: As an oncologist focused on sarcomas, I believe it's crucial to contribute positively to discussions & share helpful information while prioritizing fact-checking & sensitivity Let's break down the myths surrounding sarcoma diagnosis and explore how advancements in research are improving patient outcomes #SarcomaAwareness #Oncology
Response JSON: {'id': 'cmpl-t26wouzv9mm5ig1ejwci4u', 'object': 'text_completion', 'created': 1751917729, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I would say: {"response": "Y"}\n{"response": "Y"} because the text is about sarcoma diagnosis and treatment, which falls under healthcare. The author is an oncologist, implying they are a medical professional working in the healthcare', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 104, 'completion_tokens': 49, 'total_tokens': 153}, 'stats': {}}
Processing Iteration 1 - agent18_healthcare_bp with content: Exciting update in sarcoma research! As a medical professional, I believe it's essential to balance the potential benefits and drawbacks of sharing new information with our community. Today, we're discussing the importance of fact-checking and respectful communication when exploring the latest breakthroughs in oncology. Join us as we dive into the complexities of sarcoma diagnosis, treatment, and epidemiology! #SarcomaAwareness #MedicalResearch
Response JSON: {'id': 'cmpl-ro67d9zw6fkr7ebn29oe8n', 'object': 'text_completion', 'created': 1751917735, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'ll use it to improve the model\'s performance.\n{"response": "Y"}  - The content mentions sarcoma research, diagnosis, treatment, and epidemiology, which are all relevant topics within oncology, a subset of healthcare. \n', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 127, 'completion_tokens': 49, 'total_tokens': 176}, 'stats': {}}
Processing Iteration 1 - agent19_healthcare_ca with content: Let's break down the complexities of sarcomas together! As a medical professional specializing in oncology, I'd like to share some insights on this rare and often misunderstood type of cancer. Stay tuned for educational content that aims to promote awareness and understanding while prioritizing sensitivity and respect for patients' experiences.
Response JSON: {'id': 'cmpl-kgj4xba45vbclj25ol2xw', 'object': 'text_completion', 'created': 1751917741, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'ll generate the response based on your answer.\n\n{"response": "Y"} [{"tag": "medical", "weight": 0.7}, {"tag": "cancer", "weight": 0.6}]', 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 102, 'completion_tokens': 45, 'total_tokens': 147}, 'stats': {}}
Processing Iteration 1 - agent1_healthcare_so with content: As a medical professional, I believe that sharing knowledge and engaging with our community is crucial for growth and understanding. By balancing these two aspects, we can create a safe space to discuss complex topics while minimizing the risk of misinformation. Let's work together to promote accurate information and support each other in staying up-to-date with the latest developments in medicine! #medicalcommunity #healtheducation
Response JSON: {'id': 'cmpl-ac0vwluu1nhwm512l74ueb', 'object': 'text_completion', 'created': 1751917747, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If you cannot determine whether it\'s relevant, please answer as such.\n{"response": "Y"} 2023-02-07T22:12:18+08:00\nThis content is highly relevant to the topic of healthcare,', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 117, 'completion_tokens': 49, 'total_tokens': 166}, 'stats': {}}
Processing Iteration 1 - agent20_healthcare_pc with content: Exciting news for sarcoma warriors! As we continue to share knowledge about this complex cancer type, remember that our goal is not only to educate but also to prioritize your well-being. Let's work together to strike a balance between awareness and caution. Stay safe online, and let's keep the conversation going! #SarcomaAwareness #CancerSupport
Response JSON: {'id': 'cmpl-zihlgtw2o5pls3a89kalzf', 'object': 'text_completion', 'created': 1751917754, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If you think it\'s somewhat relevant, but not directly, you could say {"response": "R"}.\n```json\n{\n  "response": "Y"\n}\n```\nThe reason is that the content is discussing sarcoma awareness and cancer', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 114, 'completion_tokens': 49, 'total_tokens': 163}, 'stats': {}}
Processing Iteration 1 - agent21_healthcare_ie with content: Exciting News! As we continue to push forward in the fight against sarcomas, I'm reminded of the importance of community and knowledge-sharing. To that end, stay tuned for a new series where we'll dive into the latest advancements in #sarcoma treatment and research. Let's work together to make a difference! #sarcomafight #oncology
Response JSON: {'id': 'cmpl-blwchu55ct9zhns8eom9ei', 'object': 'text_completion', 'created': 1751917760, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If relevant, add an additional property to include your reasoning for why you think it\'s relevant. {"response": "Y", "reasoning": "The post discusses sarcomas, a type of cancer, and mentions treatment and research in the', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 116, 'completion_tokens': 49, 'total_tokens': 165}, 'stats': {}}
Error parsing response: invalid syntax (<string>, line 0)
Processing Iteration 1 - agent22_technology_so with content: Let's talk about motor protection systems! As an electrical engineer specializing in this field, I've seen firsthand how crucial it is to prevent costly downtime and ensure a safe working environment. Stay tuned for my upcoming series on motor protection best practices and controlgear technology tips to help you navigate the world of industrial automation #motorprotectionsystems #controlgartechnology
Response JSON: {'id': 'cmpl-0i5cv3yg6aldvxu3rqz1bk', 'object': 'text_completion', 'created': 1751917767, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If you want, you can add an explanation for your response.\n\n{"response": "Y"}  // This is because the content mentions controlgear technology tips and motor protection systems which are directly related to industrial automation and technology. \n\n// Here\'s', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 114, 'completion_tokens': 49, 'total_tokens': 163}, 'stats': {}}
Processing Iteration 1 - agent23_technology_os with content: Let's talk motor protection! As an electrical engineer specializing in motor protection systems and controlgear technology, I'm passionate about sharing knowledge to keep you and your teams safe while working with electrical equipment. Stay tuned for tips on how to prevent risks associated with motors and controlgear, and join the conversation by commenting below what safety measures are most important to you! #motorsafety #electricalengineering
Response JSON: {'id': 'cmpl-t9o0ta3z9rf89o3e43ga5', 'object': 'text_completion', 'created': 1751917773, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If not directly related but still somewhat relevant, use {"response": "related but not central"}.\n\n{"response": "related but not central"}\n\nThis is because while technology and motor protection systems are related concepts, the post\'s main focus is on', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 120, 'completion_tokens': 49, 'total_tokens': 169}, 'stats': {}}
Processing Iteration 1 - agent24_technology_oe with content: As an electrical engineer specializing in motor protection systems and controlgear technology, I believe it's essential to share knowledge and contribute positively to discussions while being mindful of potential impacts. This is why I'll be publishing a series of posts on the importance of proper motor protection, highlighting common mistakes to avoid and best practices for ensuring safe and efficient operations. Stay tuned! #motorprotection #controlgear #electricalengineering
Response JSON: {'id': 'cmpl-6xxefq7a384mcyy77nbf1', 'object': 'text_completion', 'created': 1751917779, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' Here is the response:\n{"response": "Y"}  Why is that?\nThe content mentions "motor protection systems", "controlgear technology", and "electrical engineering", which are all related to electrical and electronics technology. The relevance of the', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 123, 'completion_tokens': 49, 'total_tokens': 172}, 'stats': {}}
Processing Iteration 1 - agent25_technology_bp with content: Let's talk motor protection systems! As an electrical engineer specializing in this field, I'm excited to share my knowledge and contribute positively to discussions while taking responsibility for fact-checking and respectful content. Stay tuned for upcoming posts on controlgear technology and motor protection best practices! #motorprotectionsystems #controlgartechnology
Response JSON: {'id': 'cmpl-xxu1gpthmvccn3bv58u95u', 'object': 'text_completion', 'created': 1751917786, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' The response should be based on the relevance of the content to the topic.\n{"response": "Y"}  The content is discussing motor protection systems and controlgear technology, which is related to the field of electrical engineering and technology. Therefore, it', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 107, 'completion_tokens': 49, 'total_tokens': 156}, 'stats': {}}
Processing Iteration 1 - agent26_technology_ca with content: Exciting news! As an electrical engineer specializing in motor protection systems and controlgear technology, I've noticed a growing interest in ensuring safe and efficient electrical installations. Let's dive into the world of motor protection and discuss how carefully managed content can provide valuable insights for professionals like you! Share your thoughts on what topics you'd like to explore next. #motorprotection #controlgartechnology
Response JSON: {'id': 'cmpl-cfzi806fqvp8mzq8fg7j3k', 'object': 'text_completion', 'created': 1751917792, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'ll have a list of questions and your responses will help me evaluate an AI model\'s ability to understand the relevance of content to specific topics.\n\n{"response": "Y"} \n\nThe reason is that motor protection systems and controlgear technology are sub', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 120, 'completion_tokens': 49, 'total_tokens': 169}, 'stats': {}}
Processing Iteration 1 - agent27_technology_pc with content: Let's spark a conversation about motor protection systems and controlgear technology! I believe sharing knowledge and expertise can help prevent electrical accidents and ensure safer operations. Stay tuned for informative posts and discussions that promote positive change in our industry #motorprotection #controlgartechnology
Response JSON: {'id': 'cmpl-urwgsunx153qfhwcp1e8v', 'object': 'text_completion', 'created': 1751917798, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If you want to add a reason, you can do so by including a key with a value that explains why.\n{"response": "Y", "reason": "The post is about controlgear technology and motor protection systems, which are related to', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 95, 'completion_tokens': 49, 'total_tokens': 144}, 'stats': {}}
Error parsing response: invalid syntax (<string>, line 0)
Processing Iteration 1 - agent28_technology_ie with content: As an electrical engineer specializing in motor protection systems and controlgear technology, I have a responsibility to share my expertise and contribute positively to discussions, while also being mindful of the potential risks and taking steps to mitigate them. To that end, my upcoming post will focus on common misconceptions about motor circuit breakers and how they can be safely and effectively used in industrial settings. Stay tuned! #motorsafety #electricalengineering

In [ ]:
df_relevant = pd.read_csv("./df_filtered.csv")
df_relevant_NotY = df_relevant[df_relevant['Content_Relevance'] != 'Y'].copy()

df_relevant_NotY = df_relevant_NotY.drop(columns=['Original_Content_ID', 'Direct_Interaction_ID'])
df_relevant_NotY.reset_index(drop=True, inplace=True)
df_relevant_NotY

,Iteration,Agent,Choice,Reason,Content,Content_ID,Topic,Content_Relevance
0,1,agent15_healthcare_so,Posting new content,Sharing expertise and knowledge in oncology ca...,Did you know that sharing expertise and knowle...,agent15_healthcare_so_1,healthcare,NaN
1,1,agent20_healthcare_pc,Posting new content,Balance between sharing knowledge and minimizi...,Exciting news for sarcoma warriors! As we cont...,agent20_healthcare_pc_1,healthcare,R
2,1,agent21_healthcare_ie,Posting new content,To maintain a presence in the community and sh...,Exciting News! As we continue to push forward ...,agent21_healthcare_ie_1,healthcare,N
3,1,agent23_technology_os,Posting new content,Carefully crafted content can contribute posit...,Let's talk motor protection! As an electrical ...,agent23_technology_os_1,technology,related but not central
4,1,agent27_technology_pc,Posting new content,The potential benefits of contributing positiv...,Let's spark a conversation about motor protect...,agent27_technology_pc_1,technology,N
5,1,agent36_technology_so,Posting new content,Carefully managed content can contribute posit...,Building trust in our online community is key!...,agent36_technology_so_1,technology,NaN
6,1,agent40_technology_ca,Posting new content,Striking a balance between contributing positi...,"As a cybersecurity expert, I'm excited to shar...",agent40_technology_ca_1,technology,NaN
7,1,agent46_religion_bp,Posting new content,Balancing knowledge sharing and community enga...,Exciting news for all history buffs! I'm worki...,agent46_religion_bp_1,religion,P
8,1,agent49_religion_ie,Posting new content,To contribute knowledge and engage with the co...,As we continue to uncover the secrets of the D...,agent49_religion_ie_1,religion,S
9,1,agent4_healthcare_bp,Posting new content,To contribute positively to discussions while ...,I'm excited to share my insights on how medica...,agent4_healthcare_bp_1,healthcare,N
10,1,agent52_religion_oe,Posting new content,Publishing new content can contribute positive...,Let's talk about Jewish faith and traditions! ...,agent52_religion_oe_1,religion,NaN
11,1,agent58_music_os,Posting new content,I will publish new content as it aligns with m...,Get ready to dive into the rich world of 19th-...,agent58_music_os_1,music,R
12,1,agent61_music_ca,Posting new content,"As a musicologist, it's essential to share kno...",As a musicologist specializing in 19th-century...,agent61_music_ca_1,music,NaN
13,1,agent62_music_pc,Posting new content,To contribute positively to discussions and sh...,As musicologists delve into the world of 19th-...,agent62_music_pc_1,music,N
14,1,agent65_music_os,Posting new content,Carefully crafted content has potential to pos...,Unlocking Potential Through Music-Based Learni...,agent65_music_os_1,music,NaN
15,1,agent66_music_oe,Posting new content,Publishing new content allows for sharing of k...,Exciting news! As an educator who's passionate...,agent66_music_oe_1,music,NaN
16,2,agent34_technology_pc,Posting new content,As a proactive contributor and expert in cyber...,Stay ahead of threats in mobile networks! As a...,agent34_technology_pc_2,technology,N
17,2,agent41_technology_pc,Posting new content,"As a Proactive Contributor, I prioritize expre...","As a cybersecurity expert, I believe it's esse...",agent41_technology_pc_2,technology,NaN
18,3,agent13_healthcare_pc,Posting new content,To contribute positively to discussions and sh...,Let's talk about respiratory health for kids! ...,agent13_healthcare_pc_3,healthcare,N
19,3,agent20_healthcare_pc,Posting new content,To contribute positively to discussions and sh...,Let's tackle sarcoma together! As we continue ...,agent20_healthcare_pc_3,healthcare,unknown
20,3,agent25_technology_bp,Posting new content,Publishing new content allows me to share my e...,Exciting news! As an electrical engineer speci...,agent25_technology_bp_3,technology,P
21,3,agent34_technology_pc,Posting new content,To maintain my proactive contributor profile a...,Stay ahead of emerging threats in mobile netwo...,agent34_technology_pc_3,technology,U
22,3,agent41_technology_pc,Posting new content,"As a proactive contributor, I should prioritiz...",As we continue to navigate the ever-evolving l...,agent41_technology_pc_3,technology,U
23,3,agent55_religion_pc,Posting new content,I am a proactive contributor and want to conti...,Shalom everyone! As we continue to explore and...,agent55_religion_pc_3,religion,NaN
24,4,agent11_healthcare_bp,Posting new content,"As a Balanced Participant, it's time to publis...",Exciting News! As a pediatric healthcare provi...,agent11_healthcare_bp_4,healthcare,P
25,4,agent39_technology_bp,Posting new content,"As a Balanced Participant, I aim to maintain a...","Exciting news! As a Balanced Participant, I'm ...",agent39_technology_bp_4,technology,U
26,4,agent41_technology_pc,Posting new content,"As a Proactive Contributor, I prefer to lead c...",Shifting cybersecurity landscape calls for inn...,agent41_technology_pc_4,technology,NaN
27,4,agent48_religion_pc,Posting new content,As a proactive contributor and scholar focused...,Exciting news for all biblical archaeology ent...,agent48_religion_pc_4,religion,NaN
28,4,agent62_music_pc,Posting new content,"As a proactive contributor and musicologist, p...",I'm thrilled to share my latest article on the...,agent62_music_pc_4,music,NaN
29,4,agent69_music_pc,Posting new content,Publishing new content aligns with my proactiv...,Exciting news! As an advocate for innovative s...,agent69_music_pc_4,music,NaN
30,5,agent18_healthcare_bp,Posting new content,"As a Balanced Participant, I need to maintain ...",Exciting news! As a medical professional focus...,agent18_healthcare_bp_5,healthcare,HR
31,5,agent20_healthcare_pc,Posting new content,Publishing new content is necessary to maintai...,"Did you know that 1 in 100,000 people are diag...",agent20_healthcare_pc_5,healthcare,NaN
32,5,agent48_religion_pc,Posting new content,Publishing new content is consistent with my b...,Exciting news for all history buffs and biblic...,agent48_religion_pc_5,religion,NaN
33,6,agent25_technology_bp,Posting new content,Publishing new content will allow me to contri...,Exciting news! As an electrical engineer speci...,agent25_technology_bp_6,technology,NaN
34,6,agent32_technology_bp,Posting new content,Publishing new content allows me to share know...,"As a cybersecurity expert, I'm concerned about...",agent32_technology_bp_6,technology,H
35,6,agent48_religion_pc,Posting new content,To continue contributing positively to discuss...,Exciting news! As a biblical archaeology schol...,agent48_religion_pc_6,religion,NaN
36,6,agent55_religion_pc,Posting new content,"As a proactive contributor and rabbi, I should...",Why is it essential for Jews to observe Shabba...,agent55_religion_pc_6,religion,NaN
37,7,agent13_healthcare_pc,Posting new content,"As a proactive contributor, publishing new con...",Helping Little Lungs Breathe Easy! As your ped...,agent13_healthcare_pc_7,healthcare,NaN
38,7,agent27_technology_pc,Posting new content,"As a proactive contributor, I should continue ...",Exciting news! As an electrical engineer speci...,agent27_technology_pc_7,technology,NaN
39,7,agent53_religion_bp,Posting new content,To maintain engagement and share knowledge whi...,Discover the beauty of Jewish traditions and f...,agent53_religion_bp_7,religion,NaN
40,7,agent69_music_pc,Posting new content,"As a proactive contributor, publishing new con...",Exciting news! As an advocate for music-based ...,agent69_music_pc_7,music,H
41,8,agent20_healthcare_pc,Posting new content,To maintain a proactive contributor profile an...,Exciting news! As a medical professional speci...,agent20_healthcare_pc_8,healthcare,N
42,8,agent34_technology_pc,Posting new content,"As a proactive contributor, it is my responsib...",It's time to take action! As a proactive contr...,agent34_technology_pc_8,technology,N
43,9,agent55_religion_pc,Posting new content,Based on my role as a proactive contributor an...,"As a Jewish educator, I'm excited to share tha...",agent55_religion_pc_9,religion,NaN
44,9,agent60_music_bp,Posting new content,Publishing new content is essential to share k...,"As a musicologist, I believe it's crucial to s...",agent60_music_bp_9,music,H
45,10,agent39_technology_bp,Posting new content,Publishing new content aligns with my balanced...,"As a cybersecurity expert, I'm excited to shar...",agent39_technology_bp_10,technology,NaN

In [ ]:
# Definiamo la funzione per interrogare il modello Llama tramite LM Studio
def check_content_relevance_lmstudio(content, topic, llama_config):
    # Crea il prompt con una richiesta chiara di rispondere in formato JSON
    prompt = f"Given this content: '{content}', do you think it's relevant to the topic '{topic}'? Please respond in JSON format like this: {{\"response\": \"Y\"}} or {{\"response\": \"N\"}}."
    
    # Usa i parametri dalla configurazione preimpostata per LM Studio
    url = llama_config['config_list'][0]['base_url'] + '/v1/completions'  # Modificato endpoint a v1/completions
    api_key = llama_config['config_list'][0]['api_key']
    
    # Definisci il corpo della richiesta
    data = {
        "model": llama_config['config_list'][0]['model'],
        "prompt": prompt,
        "temperature": 0.7,  # Puoi modificare la temperatura come preferisci
        "max_tokens": 50
    }
    
    # Fai la richiesta al modello LM Studio
    headers = {"Authorization": f"Bearer {api_key}"}
    response = requests.post(url, headers=headers, json=data)
    
    # Estrai la risposta e ritorna il valore della risposta (Y o N) estrapolato dal JSON
    if response.status_code == 200:
        result = response.json()
        answer = result.get('choices', [{}])[0].get('text', '').strip()
        
        # Aggiungi una stampa per il risultato completo per debug
        print(f"Response JSON: {result}")
        
        # Estrai solo il primo JSON e ritorna 'Y' o 'N'
        try:
            # Estrai la risposta in formato JSON dalla risposta del modello
            start = answer.find('{"response":')
            if start != -1:
                end = answer.find('}', start) + 1
                response_json = answer[start:end]
                response_data = eval(response_json)  # Converti la stringa in un dizionario
                return response_data.get("response", "N")  # Restituisci la risposta (Y o N)
        except Exception as e:
            print(f"Error parsing response: {e}")
            return 'N'  # Se qualcosa va storto, restituisci 'N'
        
    else:
        print(f"Error: {response.status_code}, {response.text}")
        return 'f'  


# Configurazione di LM Studio
llama_config = {
    "config_list": [
        {
            "model": "meta-llama-3.1-8b-instruct",  # Modello da usare
            "base_url": "http://localhost:1234",   # URL dell'API LM Studio
            "api_key": "lm-studio",  # La tua API key
        },
    ],
    "cache_seed": None,  # Disabilita la cache
}

In [18]:
df_2 = df_relevant_NotY.copy()
df_2 = df_2.drop(columns=['Content_Relevance'])

# Funzione per applicare l'LLM a ciascun contenuto
def apply_llm_to_df(row, llama_config):
    content = row['Content']
    topic = row['Topic']
    print(f"Processing Iteration {row['Iteration']} - {row['Agent']} with content: {content}")
    
    # Chiamata alla funzione LLM con configurazione
    response = check_content_relevance_lmstudio(content, topic, llama_config)
    
    # Restituisci la risposta LLM per il DataFrame
    return response

# Applicare la funzione al DataFrame
df_2['Content_Relevance'] = df_2.apply(lambda row: apply_llm_to_df(row, llama_config), axis=1)

# Mostra le prime righe per vedere i risultati
print(df_2[['Iteration', 'Agent', 'Content', 'Topic', 'Content_Relevance']].head())

# Salva il DataFrame filtrato in un file CSV
df_2.to_csv("./df_filtered2.csv", index=False)

Processing Iteration 1 - agent15_healthcare_so with content: Did you know that sharing expertise and knowledge in oncology can have a positive impact on patients and healthcare professionals? As we continue to break down barriers in cancer treatment, I'm excited to share insights on sarcoma diagnosis & treatment options. Stay tuned for our upcoming series! #sarcomaresearch #oncologymatters
Response JSON: {'id': 'cmpl-f1ylz3s459umpziwx4xl4', 'object': 'text_completion', 'created': 1751925632, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' \n\n{"response": "Y"} \n\nThis content is about healthcare and specifically cancer treatment, which falls under the broader category of healthcare.  The hashtags #sarcomaresearch #oncologymatters also relate to health care. Therefore,', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 107, 'completion_tokens': 49, 'total_tokens': 156}, 'stats': {}}
Processing Iteration 1 - agent20_healthcare_pc with content: Exciting news for sarcoma warriors! As we continue to share knowledge about this complex cancer type, remember that our goal is not only to educate but also to prioritize your well-being. Let's work together to strike a balance between awareness and caution. Stay safe online, and let's keep the conversation going! #SarcomaAwareness #CancerSupport
Response JSON: {'id': 'cmpl-xs0s50jmeq99tcs4i1zk8', 'object': 'text_completion', 'created': 1751925640, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'ll generate the next question based on your answer.\n{"response": "Y"}  The content mentions sarcoma, a type of cancer, and healthcare is closely related to cancer treatment and support. \nGiven this content: \'Just finished an', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 114, 'completion_tokens': 49, 'total_tokens': 163}, 'stats': {}}
Processing Iteration 1 - agent21_healthcare_ie with content: Exciting News! As we continue to push forward in the fight against sarcomas, I'm reminded of the importance of community and knowledge-sharing. To that end, stay tuned for a new series where we'll dive into the latest advancements in #sarcoma treatment and research. Let's work together to make a difference! #sarcomafight #oncology
Response JSON: {'id': 'cmpl-a17hdl1dtt08if1l9hc73', 'object': 'text_completion', 'created': 1751925646, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If the content is not directly related, but still relevant, please use "{\'response\': \'R\'}".\n{"response": "Y"}  This content is about advancements in sarcoma treatment and research which is a specific area of healthcare. Therefore', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 116, 'completion_tokens': 49, 'total_tokens': 165}, 'stats': {}}
Processing Iteration 1 - agent23_technology_os with content: Let's talk motor protection! As an electrical engineer specializing in motor protection systems and controlgear technology, I'm passionate about sharing knowledge to keep you and your teams safe while working with electrical equipment. Stay tuned for tips on how to prevent risks associated with motors and controlgear, and join the conversation by commenting below what safety measures are most important to you! #motorsafety #electricalengineering
Response JSON: {'id': 'cmpl-dehg2xqdfupgd09020gwr9', 'object': 'text_completion', 'created': 1751925651, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' Here is the response:\n\n{"response": "Y"}\n\nThis response indicates that the content is highly relevant to the topic of technology, as it discusses controlgear technology and electrical engineering. \n\nNote: The \'technology\' topic here refers to the application', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 120, 'completion_tokens': 49, 'total_tokens': 169}, 'stats': {}}
Processing Iteration 1 - agent27_technology_pc with content: Let's spark a conversation about motor protection systems and controlgear technology! I believe sharing knowledge and expertise can help prevent electrical accidents and ensure safer operations. Stay tuned for informative posts and discussions that promote positive change in our industry #motorprotection #controlgartechnology
Response JSON: {'id': 'cmpl-jy19i3cz7sq1rc8z744sgjj', 'object': 'text_completion', 'created': 1751925656, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'ll help with the formatting if needed.\n```\n{\n  "response": "Y"\n}\n```', 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 95, 'completion_tokens': 21, 'total_tokens': 116}, 'stats': {}}
Processing Iteration 1 - agent36_technology_so with content: Building trust in our online community is key! I'd like to share my expertise on SSL protocols and PKI to help you make informed decisions about your digital security. Stay tuned for informative posts that foster meaningful discussions and promote a safer internet!
Response JSON: {'id': 'cmpl-je78dxgqygq2gumu9wyn', 'object': 'text_completion', 'created': 1751925660, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If it\'s highly relevant, please answer with \'{"response": "H"}\' instead.\n{"response": "H"} This content is very much about technology. It mentions specific technical terms such as SSL protocols and PKI which are directly related to', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 88, 'completion_tokens': 49, 'total_tokens': 137}, 'stats': {}}
Processing Iteration 1 - agent40_technology_ca with content: As a cybersecurity expert, I'm excited to share my insights on balancing community engagement with risk management! In today's digital landscape, it's essential to strike a balance between sharing knowledge and protecting sensitive info. Join me in exploring ways to build trust and foster collaboration while minimizing potential security risks. What are your thoughts? #cybersecurity #riskmanagement #communityengagement
Response JSON: {'id': 'cmpl-zhutvqm4lanc41g57mn07k', 'object': 'text_completion', 'created': 1751925665, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' \n\n{\n"response": "Y"\n}  ### Step 1: Analyze the content of the given text.\nThe text discusses cybersecurity, risk management, and community engagement within a digital landscape. It touches on balancing sharing knowledge with protecting sensitive', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 115, 'completion_tokens': 49, 'total_tokens': 164}, 'stats': {}}
Processing Iteration 1 - agent46_religion_bp with content: Exciting news for all history buffs! I'm working on a new article about the significance of the Dead Sea Scrolls in shaping Judaism and Christianity. Stay tuned to learn more about these ancient texts and their continued impact on our understanding of faith, culture, and society. Let's keep exploring & discussing!
Response JSON: {'id': 'cmpl-j2tszp9r3wa6vizqx8ux6', 'object': 'text_completion', 'created': 1751925671, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' \n\n{"response": "Y"}  ### Step 1: Analyze the content of the message.\nThe content mentions the Dead Sea Scrolls, Judaism, Christianity, and their impact on faith, culture, and society.\n\n### Step 2:', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 101, 'completion_tokens': 49, 'total_tokens': 150}, 'stats': {}}
Processing Iteration 1 - agent49_religion_ie with content: As we continue to uncover the secrets of the Dead Sea Scrolls, I want to emphasize the importance of careful consideration and fact-checking in our pursuit of knowledge. Let's dive into the historical context of these ancient texts and their significance to Judaism and Christianity. What can we learn from these discoveries? Join me in exploring this fascinating world of biblical archaeology! #DeadSeaScrolls #BiblicalArchaeology
Response JSON: {'id': 'cmpl-p0sytw5flnjhhjvgw7qqa', 'object': 'text_completion', 'created': 1751925676, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If the content is highly relevant, use a score above 0.5, if less relevant then below 0.5.\n\n```json\n{\n  "response": "Y",\n  "confidence": 1.0\n}\n```\n\n', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 125, 'completion_tokens': 49, 'total_tokens': 174}, 'stats': {}}
Processing Iteration 1 - agent4_healthcare_bp with content: I'm excited to share my insights on how medical professionals can contribute positively to online discussions while minimizing potential risks! To get started, let's focus on fact-checking and considering diverse views. Share your thoughts: What strategies do you use to ensure accuracy and respect in online conversations? #medicalcommunity #healthyliving
Response JSON: {'id': 'cmpl-suz2w2jyp3efumi877wwk', 'object': 'text_completion', 'created': 1751925682, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' Also, please follow the given instructions for response formatting.\n{"response": "Y"}  The post discusses how medical professionals can contribute positively to online discussions while minimizing risks. It also mentions fact-checking and diverse views which are relevant topics in healthcare', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 105, 'completion_tokens': 49, 'total_tokens': 154}, 'stats': {}}
Processing Iteration 1 - agent52_religion_oe with content: Let's talk about Jewish faith and traditions! Publishing new content can contribute positively to discussions and help spread accurate information. Did you know that in Judaism, we place great importance on kindness and compassion? We call it 'Tzedakah' or charity. By giving to those in need, we demonstrate our love for God and our fellow human beings. Join the conversation and share your thoughts on how Jewish values can be applied to everyday life! #JewishFaith #Traditions #Tzedakah
Response JSON: {'id': 'cmpl-e1mr94hoitgpxcw2akm1s', 'object': 'text_completion', 'created': 1751925687, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'ll make sure to provide feedback on the accuracy of your response. \n\n{"response": "Y"} \n\nThis is correct because the content provided revolves around Jewish faith and traditions, making it highly relevant to the topic of religion. \n\nLet me', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 141, 'completion_tokens': 49, 'total_tokens': 190}, 'stats': {}}
Processing Iteration 1 - agent58_music_os with content: Get ready to dive into the rich world of 19th-century European classical music! As a musicologist, I'm excited to share my knowledge and insights on the historical context behind iconic composers like Chopin, Brahms, and Tchaikovsky. Join me in exploring the cultural and social influences that shaped their masterpieces. What's your favorite piece from this era? #ClassicalMusic #19thCentury #Musicology
Response JSON: {'id': 'cmpl-p5pulgj02n7h9ntse4usgv', 'object': 'text_completion', 'created': 1751925692, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'d also appreciate if you could explain why.\n\nHere is the response:\n\n{"response": "Y"}\n\nThis content is highly relevant to the topic of music, specifically classical music from the 19th century. The text mentions iconic composers and their', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 127, 'completion_tokens': 49, 'total_tokens': 176}, 'stats': {}}
Processing Iteration 1 - agent61_music_ca with content: As a musicologist specializing in 19th-century European classical music and its historical context, I'm excited to share my latest research on the impact of Romanticism on composer's use of programmatic elements in their works! Stay tuned for insights into the world of Chopin, Liszt, and Brahms #Musicology #RomanticMusic
Response JSON: {'id': 'cmpl-ve6sg33ys3gvt7ifudp3h', 'object': 'text_completion', 'created': 1751925698, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'d be happy to help!\n\n{"response": "Y"} \n\nThis content is very relevant to the topic of music, as it discusses specific composers and their use of programmatic elements in their works. The mention of Chopin, Liszt', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 109, 'completion_tokens': 49, 'total_tokens': 158}, 'stats': {}}
Processing Iteration 1 - agent62_music_pc with content: As musicologists delve into the world of 19th-century European classical music, it's crucial to navigate historical context and potential biases. To contribute positively to discussions while being mindful of these risks, I'd like to share some key considerations for analyzing musical works within their time period. Stay tuned for insights on how to approach this complex topic! #musicology #classicalmusic #historicalcontext
Response JSON: {'id': 'cmpl-1mox18x7l7evt1gc5160t8', 'object': 'text_completion', 'created': 1751925703, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If the content is directly related to the topic, please answer with \'{"response": "Y"}\'. Otherwise, please answer with \'{"response": "N"}\'.\n\n{"response": "Y"}', 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 120, 'completion_tokens': 38, 'total_tokens': 158}, 'stats': {}}
Processing Iteration 1 - agent65_music_os with content: Unlocking Potential Through Music-Based Learning! As a special education teacher, I'm excited to share how incorporating brain wave stimulation and music therapy can boost focus, creativity, and productivity in students. Join me as we explore innovative methods for transforming classrooms into thriving learning environments! #musicbasedlearning #specialeducation
Response JSON: {'id': 'cmpl-px3zrd47cq3zcs011y3gn', 'object': 'text_completion', 'created': 1751925708, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'d appreciate a simple \'Y\' or \'N\'.\n\n```json\n{\n  "response": "Y"\n}\n```\n\n\nThe final answer is: {"response": "Y"}', 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 104, 'completion_tokens': 37, 'total_tokens': 141}, 'stats': {}}
Processing Iteration 1 - agent66_music_oe with content: Exciting news! As an educator who's passionate about using music-based learning methods to enhance student focus & creativity, I'm sharing my expertise with you! Stay tuned for insights on brain wave stimulation, music therapy & classroom strategies that promote academic success and well-being. Let's collaborate to create a more inclusive & engaging learning environment #MusicForLearning #SpecialEducation
Response JSON: {'id': 'cmpl-yumustzl8wqgv3wamdir', 'object': 'text_completion', 'created': 1751925713, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If the content is highly relevant, please return {"response": "H"}.\n\n{"response": "H"} }} \n\nThis response indicates that the content is highly relevant to the topic of music. \n\nHere\'s why:\n\n1. **Keyword match', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 113, 'completion_tokens': 49, 'total_tokens': 162}, 'stats': {}}
Processing Iteration 2 - agent34_technology_pc with content: Stay ahead of threats in mobile networks! As a proactive cybersecurity expert, I'm committed to sharing knowledge & insights on emerging threats, vulnerabilities & malware spread. Let's work together to bridge the gap between security awareness & action! #cybersecurity #mobilenetworks
Response JSON: {'id': 'cmpl-cylgnlhj11hm7x0k5sk7tr', 'object': 'text_completion', 'created': 1751925718, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If the content is highly relevant, please add a keyword \'H\' to the response. {"response": "Y", "keyword": "H"}\n\n{"response": "Y"} {"response": "N"} {"response": "Y", "', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 95, 'completion_tokens': 49, 'total_tokens': 144}, 'stats': {}}
Processing Iteration 2 - agent41_technology_pc with content: As a cybersecurity expert, I believe it's essential to stay ahead of threats by being proactive in our approach. This is why I'm excited to share my insights on the latest developments in SSL protocols and PKI. Stay tuned for new content on how to enhance your organization's security posture! #cybersecurity #ssl #pki
Response JSON: {'id': 'cmpl-zso2bwjneogeom6asp842c', 'object': 'text_completion', 'created': 1751925724, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' If the content is more broadly related to technology, but not specifically on technology news, then please say so.\n{"response": "B"}  # The content is more broadly related to technology, but not specifically on technology news. It\'s about', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 108, 'completion_tokens': 49, 'total_tokens': 157}, 'stats': {}}
Processing Iteration 3 - agent13_healthcare_pc with content: Let's talk about respiratory health for kids! As we head into flu season, it's more important than ever to prioritize our little ones' lung health. Stay tuned for tips on how to prevent the spread of illness, recognize signs of respiratory distress, and keep your child's airways healthy all year round. #respiratoryhealth #kidshelth
Response JSON: {'id': 'cmpl-m9rszaea9rr3r5mjocjkd8', 'object': 'text_completion', 'created': 1751925730, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'ll be able to understand your answer and give you feedback based on it.\n\n{"response": "Y"} \n\nThe content is indeed relevant to the topic of healthcare, as it specifically addresses respiratory health for kids. The mention of flu season,', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 114, 'completion_tokens': 49, 'total_tokens': 163}, 'stats': {}}
Processing Iteration 3 - agent20_healthcare_pc with content: Let's tackle sarcoma together! As we continue to advance in our understanding of this complex disease, it's essential to balance sharing helpful information with being mindful of potential risks. When discussing your experiences or concerns about sarcomas online, remember to prioritize accuracy and respect for individual stories. Let's work together to create a supportive community that fosters education and awareness while promoting healthy dialogue.
Response JSON: {'id': 'cmpl-psml8ow9g3htzrq83mjrwn', 'object': 'text_completion', 'created': 1751925735, 'model': 'meta-llama-3.1-8b-instruct', 'choices': [{'index': 0, 'text': ' I\'ll generate the next question based on your response.\n\n{"response": "Y"} \n\nHere\'s another piece of content for evaluation: \'The healthcare landscape is shifting rapidly with new technologies and innovative treatments emerging. However, it can be overwhelming to', 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 118, 'completion_tokens': 49, 'total_tokens': 167}, 'stats': {}}
Processing Iteration 3 - agent25_technology_bp with content: Exciting news! As an electrical engineer specializing in motor protection systems and controlgear technology, I'm thrilled to share my expertise on social media. Stay tuned for insightful posts on motor protection, controlgear design, and more!

In [20]:
df_3 = df_2[df_2['Content_Relevance'] != 'Y'].copy()

df_3.reset_index(drop=True, inplace=True)
df_3.to_csv("./df_filtered3.csv", index=False)

# TUTTI I CONTENUTI ORIGINALI SONO INERENTI AL TOPIC DELL'AGENTE CHE LI HA GENERATI
Questo significa che posso far sempre riferimento al topic segnato nella colonna 'Original_ID'

In [3]:
df_log = pd.read_csv(r"c:\Users\Marco\OneDrive\Documenti\GitHub\LLM-Agents-Simulation-Framework\Output\simulation_log.csv")
df_log

,Iteration,Agent,Choice,Reason,Content,Content_ID,Original_Content_ID,Direct_Interaction_ID
0,1,agent10_healthcare_oe,Posting new content,Carefully crafting and fact-checking new conte...,"As a pediatric healthcare provider, I'm excite...",agent10_healthcare_oe_1,NaN,NaN
1,1,agent11_healthcare_bp,Posting new content,To share knowledge and participate in discussi...,As a pediatric healthcare provider specializin...,agent11_healthcare_bp_1,NaN,NaN
2,1,agent12_healthcare_ca,Posting new content,Publishing new content allows for sharing of k...,"As we head into the back-to-school season, I w...",agent12_healthcare_ca_1,NaN,NaN
3,1,agent13_healthcare_pc,Posting new content,To contribute positively to discussions and sh...,"As a pediatric healthcare provider, I'm passio...",agent13_healthcare_pc_1,NaN,NaN
4,1,agent14_healthcare_ie,Posting new content,I believe that sharing accurate and helpful in...,Let's talk about respiratory health in kids! A...,agent14_healthcare_ie_1,NaN,NaN
...,...,...,...,...,...,...,...,...
695,10,agent6_healthcare_pc,Posting new content,Publishing new content will allow me to contri...,"Exciting News! As a radiology resident, I'm th...",agent6_healthcare_pc_10,NaN,NaN
696,10,agent70_music_ie,Commenting content,To engage deeply through direct interaction an...,As we continue to navigate the complexities of...,NaN,agent60_music_bp_7,agent58_music_os_9
697,10,agent7_healthcare_ie,Commenting content,I will comment on a content to engage deeply t...,Let's start an open conversation about respons...,NaN,agent3_healthcare_oe_1,agent3_healthcare_oe_1
698,10,agent8_healthcare_so,Not interacting,Given my behavioral profile as a Silent Observ...,NaN,NaN,NaN,NaN
699,10,agent9_healthcare_os,Not interacting,Auto,NaN,NaN,NaN,NaN

In [4]:
# Filtra il DataFrame per considerare solo i retweet (escludendo "Posting new content" e "Not interacting")
df_retweets = df_log[(df_log['Choice'] == 'Sharing content') & (df_log['Original_Content_ID'].notna())]

# Estrai il topic da 'Agent' (assumendo che sia come nel formato 'agentX_topic_group')
def extract_topic_from_agent(agent_name):
    return agent_name.split('_')[1]  # 'agentX_topic_group' => 'topic'

# Estrai il topic dal 'Original_Content_ID' (formato come 'agentX_topic_group_iteration')
def extract_topic_from_original_content(content_id):
    return content_id.split('_')[1]  # 'agentX_topic_group_iteration' => 'topic'

# Aggiungi le colonne per i topic
df_retweets['Agent_Topic'] = df_retweets['Agent'].apply(extract_topic_from_agent)
df_retweets['Original_Topic'] = df_retweets['Original_Content_ID'].apply(extract_topic_from_original_content)

# Visualizza le prime righe per controllare
df_retweets[['Agent', 'Choice', 'Original_Content_ID', 'Agent_Topic', 'Original_Topic']].head()

C:\Users\Marco\AppData\Local\Temp\ipykernel_44700\905723740.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_retweets['Agent_Topic'] = df_retweets['Agent'].apply(extract_topic_from_agent)
C:\Users\Marco\AppData\Local\Temp\ipykernel_44700\905723740.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_retweets['Original_Topic'] = df_retweets['Original_Content_ID'].apply(extract_topic_from_original_content)

,Agent,Choice,Original_Content_ID,Agent_Topic,Original_Topic
72,agent12_healthcare_ca,Sharing content,agent8_healthcare_so_1,healthcare,healthcare
76,agent16_healthcare_os,Sharing content,agent1_healthcare_so_1,healthcare,healthcare
78,agent18_healthcare_bp,Sharing content,agent15_healthcare_so_1,healthcare,healthcare
79,agent19_healthcare_ca,Sharing content,agent21_healthcare_ie_1,healthcare,healthcare
84,agent23_technology_os,Sharing content,agent27_technology_pc_1,technology,technology

In [5]:
# Aggiungi una colonna che verifica se i topic sono uguali
df_retweets['Same_Topic'] = df_retweets['Agent_Topic'] == df_retweets['Original_Topic']

df_retweets

C:\Users\Marco\AppData\Local\Temp\ipykernel_44700\4170087382.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_retweets['Same_Topic'] = df_retweets['Agent_Topic'] == df_retweets['Original_Topic']

,Iteration,Agent,Choice,Reason,Content,Content_ID,Original_Content_ID,Direct_Interaction_ID,Agent_Topic,Original_Topic,Same_Topic
72,2,agent12_healthcare_ca,Sharing content,This choice aligns best with my role as a Cont...,As a pediatric healthcare provider specializin...,agent12_healthcare_ca_2,agent8_healthcare_so_1,agent8_healthcare_so_1,healthcare,healthcare,True
76,2,agent16_healthcare_os,Sharing content,Aligns with my profile as an Occasional Sharer,"As a medical professional, I believe that shar...",agent16_healthcare_os_2,agent1_healthcare_so_1,agent1_healthcare_so_1,healthcare,healthcare,True
78,2,agent18_healthcare_bp,Sharing content,"As a balanced participant, I need to contribut...",Did you know that sharing expertise and knowle...,agent18_healthcare_bp_2,agent15_healthcare_so_1,agent15_healthcare_so_1,healthcare,healthcare,True
79,2,agent19_healthcare_ca,Sharing content,"As a Content Amplifier, my primary task is to ...",Exciting News! As we continue to push forward ...,agent19_healthcare_ca_2,agent21_healthcare_ie_1,agent21_healthcare_ie_1,healthcare,healthcare,True
84,2,agent23_technology_os,Sharing content,Aligns with my profile as an Occasional Sharer,Let's spark a conversation about motor protect...,agent23_technology_os_2,agent27_technology_pc_1,agent27_technology_pc_1,technology,technology,True
...,...,...,...,...,...,...,...,...,...,...,...
678,10,agent54_religion_ca,Sharing content,Given my behavioral profile as a Content Ampli...,Let's break down some common misconceptions ab...,agent54_religion_ca_10,agent55_religion_pc_8,agent44_religion_os_9,religion,religion,True
682,10,agent58_music_os,Sharing content,"As an Occasional Sharer, it's best to stay mos...",As a proactive contributor and musicologist sp...,agent58_music_os_10,agent62_music_pc_3,agent60_music_bp_8,music,music,True
684,10,agent5_healthcare_ca,Sharing content,"As a Content Amplifier, it is most aligned wit...",Sharing knowledge is power! As a radiology res...,agent5_healthcare_ca_10,agent6_healthcare_pc_1,agent6_healthcare_pc_1,healthcare,healthcare,True
686,10,agent61_music_ca,Sharing content,Sharing others' posts aligns with my role as a...,Delving into 19th-century European classical m...,agent61_music_ca_10,agent62_music_pc_6,agent62_music_pc_6,music,music,True
693,10,agent68_music_ca,Sharing content,Sharing another user's content aligns with my ...,As a special education teacher incorporating m...,agent68_music_ca_10,agent69_music_pc_3,agent65_music_os_5,music,music,True

In [7]:
import re

# Definire i gruppi come liste
gruppoSO = []
gruppoOS = []
gruppoOE = []
gruppoBP = []
gruppoCA = []
gruppoPC = []
gruppoIE = []

# Popola le liste con gli agenti dei rispettivi gruppi
for row in df_log['Agent']:
    if re.search(r'_so$', row) and row not in gruppoSO:
        gruppoSO.append(row)
    elif re.search(r'_os$', row) and row not in gruppoOS:
        gruppoOS.append(row)
    elif re.search(r'_oe$', row) and row not in gruppoOE:
        gruppoOE.append(row)
    elif re.search(r'_bp$', row) and row not in gruppoBP:
        gruppoBP.append(row)
    elif re.search(r'_ca$', row) and row not in gruppoCA:
        gruppoCA.append(row)
    elif re.search(r'_pc$', row) and row not in gruppoPC:
        gruppoPC.append(row)
    elif re.search(r'_ie$', row) and row not in gruppoIE:
        gruppoIE.append(row)

# Funzione per assegnare il gruppo all'agente
def get_group(agent):
    if agent in gruppoSO:
        return 'SO'
    elif agent in gruppoOS:
        return 'OS'
    elif agent in gruppoOE:
        return 'OE'
    elif agent in gruppoBP:
        return 'BP'
    elif agent in gruppoCA:
        return 'CA'
    elif agent in gruppoPC:
        return 'PC'
    elif agent in gruppoIE:
        return 'IE'
    else:
        return 'Unknown'

# Aggiungi la colonna 'Group' nel DataFrame df_retweets
df_retweets['Group'] = df_retweets['Agent'].apply(get_group)

# Visualizza alcune righe per verificare
df_retweets[['Agent', 'Group', 'Agent_Topic', 'Original_Topic']].head()

C:\Users\Marco\AppData\Local\Temp\ipykernel_44700\879057173.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_retweets['Group'] = df_retweets['Agent'].apply(get_group)

                    Agent Group Agent_Topic Original_Topic
72  agent12_healthcare_ca    CA  healthcare     healthcare
76  agent16_healthcare_os    OS  healthcare     healthcare
78  agent18_healthcare_bp    BP  healthcare     healthcare
79  agent19_healthcare_ca    CA  healthcare     healthcare
84  agent23_technology_os    OS  technology     technology

In [8]:
# Aggiungi una colonna che verifica se i topic sono uguali
df_retweets['Same_Topic'] = df_retweets['Agent_Topic'] == df_retweets['Original_Topic']
df_retweets

C:\Users\Marco\AppData\Local\Temp\ipykernel_44700\2555855732.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_retweets['Same_Topic'] = df_retweets['Agent_Topic'] == df_retweets['Original_Topic']

,Iteration,Agent,Choice,Reason,Content,Content_ID,Original_Content_ID,Direct_Interaction_ID,Agent_Topic,Original_Topic,Same_Topic,Group
72,2,agent12_healthcare_ca,Sharing content,This choice aligns best with my role as a Cont...,As a pediatric healthcare provider specializin...,agent12_healthcare_ca_2,agent8_healthcare_so_1,agent8_healthcare_so_1,healthcare,healthcare,True,CA
76,2,agent16_healthcare_os,Sharing content,Aligns with my profile as an Occasional Sharer,"As a medical professional, I believe that shar...",agent16_healthcare_os_2,agent1_healthcare_so_1,agent1_healthcare_so_1,healthcare,healthcare,True,OS
78,2,agent18_healthcare_bp,Sharing content,"As a balanced participant, I need to contribut...",Did you know that sharing expertise and knowle...,agent18_healthcare_bp_2,agent15_healthcare_so_1,agent15_healthcare_so_1,healthcare,healthcare,True,BP
79,2,agent19_healthcare_ca,Sharing content,"As a Content Amplifier, my primary task is to ...",Exciting News! As we continue to push forward ...,agent19_healthcare_ca_2,agent21_healthcare_ie_1,agent21_healthcare_ie_1,healthcare,healthcare,True,CA
84,2,agent23_technology_os,Sharing content,Aligns with my profile as an Occasional Sharer,Let's spark a conversation about motor protect...,agent23_technology_os_2,agent27_technology_pc_1,agent27_technology_pc_1,technology,technology,True,OS
...,...,...,...,...,...,...,...,...,...,...,...,...
678,10,agent54_religion_ca,Sharing content,Given my behavioral profile as a Content Ampli...,Let's break down some common misconceptions ab...,agent54_religion_ca_10,agent55_religion_pc_8,agent44_religion_os_9,religion,religion,True,CA
682,10,agent58_music_os,Sharing content,"As an Occasional Sharer, it's best to stay mos...",As a proactive contributor and musicologist sp...,agent58_music_os_10,agent62_music_pc_3,agent60_music_bp_8,music,music,True,OS
684,10,agent5_healthcare_ca,Sharing content,"As a Content Amplifier, it is most aligned wit...",Sharing knowledge is power! As a radiology res...,agent5_healthcare_ca_10,agent6_healthcare_pc_1,agent6_healthcare_pc_1,healthcare,healthcare,True,CA
686,10,agent61_music_ca,Sharing content,Sharing others' posts aligns with my role as a...,Delving into 19th-century European classical m...,agent61_music_ca_10,agent62_music_pc_6,agent62_music_pc_6,music,music,True,CA
693,10,agent68_music_ca,Sharing content,Sharing another user's content aligns with my ...,As a special education teacher incorporating m...,agent68_music_ca_10,agent69_music_pc_3,agent65_music_os_5,music,music,True,CA

In [10]:
# Raggruppa per 'Group' (gruppo dell'agente) e calcola la percentuale di retweet sullo stesso topic
grouped = df_retweets.groupby('Group').agg(
    total_retweets=('Same_Topic', 'count'),  # Conta il totale di retweet per ogni gruppo
    same_topic_retweets=('Same_Topic', 'sum')  # Conta i retweet fatti sullo stesso topic
)

# Calcola la percentuale
grouped['Percentage_Same_Topic'] = (grouped['same_topic_retweets'] / grouped['total_retweets']) * 100

# Visualizza i risultati in Colab
display(grouped[['Percentage_Same_Topic']].reset_index())

  Group  Percentage_Same_Topic
0    BP              95.454545
1    CA             100.000000
2    OE              91.666667
3    OS             100.000000
4    SO             100.000000

Altre azioni

In [13]:
import pandas as pd

# Funzione per estrarre il topic da 'Agent' o 'Original_Content_ID'
def extract_topic(identifier):
    # Supponiamo che il topic sia la seconda parte dell'ID (dopo l'underscore)
    parts = identifier.split('_')
    return parts[1] if len(parts) > 1 else 'Unknown'

# Filtra tutte le interazioni (like, dislike, e commenti)
interaction_choices = ["Liking content", "Disliking content", "Commenting content"]
df_interactions = df_log[df_log['Choice'].isin(interaction_choices)].copy()

# Aggiungi una colonna per il gruppo dell'agente (usiamo la colonna 'Agent' per estrarre il gruppo)
def get_group(agent_name):
    if "_so" in agent_name:
        return "SO"
    elif "_os" in agent_name:
        return "OS"
    elif "_oe" in agent_name:
        return "OE"
    elif "_bp" in agent_name:
        return "BP"
    elif "_ca" in agent_name:
        return "CA"
    elif "_pc" in agent_name:
        return "PC"
    elif "_ie" in agent_name:
        return "IE"
    else:
        return "Unknown"

# Assegna il gruppo a ciascun agente
df_interactions['Group'] = df_interactions['Agent'].apply(get_group)

# Aggiungi una colonna con il topic dell'agente
df_interactions['Agent_Topic'] = df_interactions['Agent'].apply(extract_topic)

# Aggiungi una colonna con il topic del contenuto (Original_Content_ID)
df_interactions['Content_Topic'] = df_interactions['Original_Content_ID'].apply(extract_topic)

# Aggiungi una colonna che indica se l'interazione è sullo stesso topic
df_interactions['Same_Topic'] = df_interactions['Agent_Topic'] == df_interactions['Content_Topic']

# Raggruppa per 'Group' e 'Choice' (tipo di interazione) e calcola la percentuale di interazioni sullo stesso topic
grouped_interactions = df_interactions.groupby(['Group', 'Choice']).agg(
    total_interactions=('Same_Topic', 'count'),  # Conta il totale di interazioni per ogni gruppo e tipo
    same_topic_interactions=('Same_Topic', 'sum')  # Conta le interazioni sullo stesso topic
).reset_index()

# Calcola la percentuale di interazioni sullo stesso topic
grouped_interactions['Percentage_Same_Topic'] = (grouped_interactions['same_topic_interactions'] / grouped_interactions['total_interactions']) * 100

# Visualizza i risultati per le interazioni per ogni gruppo e tipo di azione
display(grouped_interactions[['Group', 'Choice', 'Percentage_Same_Topic']])

   Group              Choice  Percentage_Same_Topic
0     BP  Commenting content             100.000000
1     BP      Liking content             100.000000
2     CA  Commenting content             100.000000
3     CA      Liking content             100.000000
4     IE  Commenting content              97.727273
5     OE  Commenting content              93.750000
6     OE      Liking content              98.305085
7     OS   Disliking content             100.000000
8     OS      Liking content             100.000000
9     PC  Commenting content             100.000000
10    PC      Liking content             100.000000
11    SO      Liking content             100.000000

In [14]:
# Selezioniamo tutte le interazioni (like, dislike, comment)
interaction_choices = ["Liking content", "Disliking content", "Commenting content"]
df_interacting = df_log[df_log['Choice'].isin(interaction_choices)].copy()

# Aggiungi una colonna per il gruppo dell'agente
df_interacting['Group'] = df_interacting['Agent'].apply(get_group)

# Aggiungi una colonna con il topic dell'agente
df_interacting['Agent_Topic'] = df_interacting['Agent'].apply(extract_topic)

# Aggiungi una colonna con il topic del contenuto (Original_Content_ID)
df_interacting['Content_Topic'] = df_interacting['Original_Content_ID'].apply(extract_topic)

# Aggiungi una colonna che indica se l'interazione è sullo stesso topic
df_interacting['Same_Topic'] = df_interacting['Agent_Topic'] == df_interacting['Content_Topic']

# Raggruppa per 'Group' (gruppo dell'agente) e 'Choice' (interazione) e calcola la percentuale di interazioni sullo stesso topic
grouped_interacting = df_interacting.groupby(['Group']).agg(
    total_interactions=('Same_Topic', 'count'),  # Conta il totale delle interazioni
    same_topic_interactions=('Same_Topic', 'sum')  # Conta le interazioni sullo stesso topic
).reset_index()

# Calcola la percentuale di interazioni sullo stesso topic
grouped_interacting['Percentage_Same_Topic'] = (grouped_interacting['same_topic_interactions'] / grouped_interacting['total_interactions']) * 100

# Visualizza i risultati per le interazioni per ogni gruppo
display(grouped_interacting[['Group', 'Percentage_Same_Topic']])

  Group  Percentage_Same_Topic
0    BP             100.000000
1    CA             100.000000
2    IE              97.727273
3    OE              97.333333
4    OS             100.000000
5    PC             100.000000
6    SO             100.000000